[profile.default]
src = "contracts"
out = "out"
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
bsc_testnet = "https://bsc-testnet-dataseed.bnbchain.org"   # chain id 97
bsc         = "https://bsc-dataseed.bnbchain.org"           # chain id 56

[etherscan]
bsc_testnet = { key = "${ETHERSCAN_API_KEY}", chain = 97 }
bsc         = { key = "${ETHERSCAN_API_KEY}", chain = 56 }
